[build]
    command = "npm run build"
    publish = "build"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        Content-Type = "text/html; charset=UTF-8"
        X-UA-Compatible = "IE=edge"
        Cache-control = "no-store"
        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:"
        X-Robots-Tag = "all"
        Vary = "User-Agent"